apiVersion: v1
kind: Service
metadata:
  name: node-tracker
  labels:
    app: node-tracker
spec:
  type: LoadBalancer
  ports:
   - port: 80
     protocol: TCP
     targetPort: 8080
  selector:
    app: node-tracker
